#!/bin/sh
[ -z ${AWS_ACCESS_KEY} ] && echo "AWS_ACCESS_KEY MUST BE SET!" && exit 1
[ -z ${AWS_SECRET_KEY} ] && echo "AWS_SECRET_KEY MUST BE SET!" && exit 1


[ -z ${IP_ADDRESS} ] && IP_ADDRESS=52.50.72.168

java -DawsAccessKey="${AWS_ACCESS_KEY}" \
    -DawsSecretKey="${AWS_SECRET_KEY}" \
    -DipAddress="${IP_ADDRESS}" \
    -cp /target/automation-grid.jar org.openqa.grid.selenium.GridLauncher \
    -role hub \
    -servlets "com.rmn.qa.servlet.AutomationTestRunServlet","com.rmn.qa.servlet.StatusServlet"



#-DPOOL_MAX=1024 
#-DawsAccessKey=AKIAJIK2AYNQADXNCXBQ 
#-DawsSecretKey=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
#-DtotalNodeCount=200 
#-DipAddress="52.50.72.168" 
#-hubConfig src/main/resources/hub.static.json 
#-log grid.log 
#-jettyMaxThreads 1024


